#!/usr/bin/env bash

config="~/.config/herbstluftwm/autostart"

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4   # Use Win key as $Mod
hc keybind $Mod-z spawn rofi -show run -theme-str 'window {width: 25%;}'
hc keybind XF86AudioLowerVolume spawn /etc/nixos/dotfiles/herbstluftwm/voldown.sh
hc keybind XF86AudioRaiseVolume spawn /etc/nixos/dotfiles/herbstluftwm/volup.sh
hc keybind XF86AudioMute spawn /etc/nixos/dotfiles/herbstluftwm/volmute.sh
hc keybind $Mod+Alt+Up spawn audacious --play-pause
hc keybind $Mod+Alt+Down spawn audacious --play-pause
hc keybind $Mod+Alt+Right spawn audacious --fwd
hc keybind $Mod+Alt+Left spawn audacious --rew
hc keybind $Mod-s spawn pkill polybar
hc keybind $Mod-a spawn polybar --config=/etc/nixos/dotfiles/polybar/config infobar
hc keybind Print spawn flameshot gui
hc keybind $Mod-Shift-c spawn galculator
hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-Return spawn alacritty
hc keybind $Mod-Shift-m spawn audacious
hc keybind $Mod-q remove
hc keybind $Mod-Shift-l spawn i3lock-fancy
hc keybind XF86MonBrightnessUp spawn brightnessctl set +3%
hc keybind XF86MonBrightnessDown spawn brightnessctl set 3%-
hc keybind XF86AudioNext spawn  dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Next
hc keybind XF86AudioPrev spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Previous
hc keybind XF86AudioPlay spawn dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.PlayPause
#hc keybind $Mod+r spawn XCURSOR_THEME=GoogleDot-Red runelite
#hc keybind XF86AudioPlay spawn cmus-remote -u
#hc keybind XF86AudioPrev spawn cmus-remote -r
#hc keybind XF86AudioNext spawn cmus-remote -n

# focusing clients
hc keybind $Mod-Left    focus left
hc keybind $Mod-Down    focus down
hc keybind $Mod-Up      focus up
hc keybind $Mod-Right   focus right
hc keybind $Mod-h       focus left
hc keybind $Mod-j       focus down
hc keybind $Mod-k       focus up
hc keybind $Mod-l       focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# creating frames
hc keybind $Mod-k       split   bottom  0.5
hc keybind $Mod-l       split   right   0.5
hc keybind $Mod-j       split   left    0.5
hc keybind $Mod-i       split   top     0.5

# auto-create new frame
hc keybind $Mod-Control-space split explode

# toggle floating
hc keybind $Mod-Shift-space floating toggle

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep


# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle


# mouse interaction
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# tags
tag_names=( {1..5} )
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# frame theming
hc attr theme.tiling.reset 0
hc attr theme.floating.reset 1
hc set frame_border_active_color '#777777' #outer
hc set frame_border_normal_color '#232323' #outer
hc set frame_border_width 3
hc set frame_bg_normal_color '#333333' #inner
hc set frame_bg_active_color '#C7C7C7' #inner
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set window_gap 0
hc set frame_gap 0
hc set always_show_frame 1

# window theming
hc attr theme.border_width 5
hc attr theme.normal.color '#454545'     # inactive windows
hc attr theme.urgent.color '#ff81e2'     # urgent-flag windows
hc attr theme.inner_width 3
hc attr theme.inner_color black
# note: outer width = (width) - (inner width)

# floating window theming
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black

# focused window borders
hc attr theme.active.inner_color        '#BBBBBB'
hc attr theme.active.color              '#EEEEEE'
hc attr theme.active.outer_color        '#FFFFFF'

# bg color when mouse-drag-resize
hc attr theme.background_color          '#000000'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# check for external displays
hc detect_monitors

# Autostart apps
hc spawn flameshot &
hc pad 0 25 0 0 0 &
hc spawn compton &
hc spawn polybar --config=/etc/nixos/dotfiles/polybar/config infobar &
hc spawn feh --bg-scale /etc/nixos/dotfiles/herbstluftwm/screen.png &
#hc spawn sudo mount /dev/disk/by-id/usb-Generic-_Multi-Card_20071114173400000-0:0-part1 /home/joe/Music/jcore
#hc load '(split horizontal:0.35:1 (clients vertical:0 0x120000e 0x1a00005 0x1400007) (split vertical:0.65:1 (clients vertical:0 0x260002c) (clients horizontal:1 0x2a0000e 0x2c0000e)))'
hc spawn xrdb ~/.Xresources &
